### ISSUE TITLE
Counter Info

### ISSUE THREAD

**Issue by NyanekoNNK** [DiamondPRO02/nsfw-game-manager#12]
Put a counter panel above the table that shows the all game count 
maybe even the steam games / manual games/ f95 games

also make an overall cum counter here how many time you did cum already xd

![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/130905090/d45c3e6e-ee1d-47a0-9ea0-80c0bdb85af2)

**Comment by DiamondCoder02** [comment]
Done in d5289ee4824f1ba6ee74ba9cc1838fd16ef03613

![image](https://github.com/DiamondCoder02/nsfw-game-manager/assets/53056204/e7460579-815b-441c-b2d9-a070f12bc9b5)
